name = "my-aad-test"
type = "webpack"
account_id = "d3765f1c5f3d3ed76be2701b78510d29"
workers_dev = true

kv_namespaces = [ 
    { binding = "AUTH_STORE", id = "3b273f42b03a445e90c8bfd93c523288" }
]

[site]
bucket = "./public"
entry-point = "."
