type = "webpack"
# account_id = ""
workers_dev = true

name = "my-auth-test"
account_id = "dc56444c4c955a1653106ccf997c1067"

# this should be replaced with your own kv namespace if you are deploying a
# version of this project! see "setup" in the readme.
kv-namespaces = [
  { binding = "AUTH_STORE", id = "dc9ec91bfd6b430ba9c4b403f885045e" }
]

[site]
bucket = './public'
entry-point = "."
